### ISSUE TITLE
Out-of-date create_ap packages

### ISSUE THREAD

**Issue by nopyhe** [archlinuxcn/repo#105]

**Comment by petronny** [comment]
It's wierd. I'll check further if it isn't updated tomorrow.

**Comment by petronny** [comment]
@lilydjwg I have no idea why it was built successfully yesterday. I can manually build it myself on the building machine by running 'sudo extra-x86-build'. 

Here is what lilacbot sent me. 

```
==>^[(B Building in chroot for [extra] (x86_64)...^[(B                                                                                                                                                               
==>^[(B Locking chroot copy [lilydjwg]...^[(Bdone^[(B                                                                                                                                                                

Traceback (most recent call last):                                                                                                                                                                                   
  File "/home/lilydjwg/bin/lilac", line 89, in build_package                                                                                                                                                         
    depends = DEPENDS.get(package, ()),                                                                                                                                                                              
  File "/home/lilydjwg/soft/lilac/lilaclib.py", line 351, in lilac_build                                                                                                                                             
    call_build_cmd(build_prefix, depend_packages, pkgs_to_build)                                                                                                                                                     
  File "/home/lilydjwg/soft/lilac/lilaclib.py", line 381, in call_build_cmd                                                                                                                                          
    build_output = run_cmd(cmd, use_pty=True)                                                                                                                                                                        
  File "/home/lilydjwg/soft/lilac/lilaclib.py", line 451, in run_cmd                                                                                                                                                 
    raise CalledProcessError(code, cmd, out)                                                                                                                                                                         
subprocess.CalledProcessError: Command '['extra-x86_64-build', '--', '--', '--holdver']' returned non-zero exit status 143                                                                                           
```

**Comment by lilydjwg** [comment]
It was killed by me because lilac mistakenly used a version of devtools only for debugging. You can update `pkgrel` to make lilac build it again.

**Comment by petronny** [comment]
create_ap at version r146 now can be found in the repo, 
>though its PKGBUILD still at version r124.
