### ISSUE TITLE
Fail to launch Bitwarden

### ISSUE THREAD

**Issue by floating-cat** [archlinuxcn/repo#1393]
### 问题类型 / Type of issues

* 打包错误 / packaging error

### 受影响的软件包 / Affected packages

* bitwarden
----

请在此补充说明。
Please describe in detail here.

I can't open Bitwarden.
This is the error message I see when I try to open Bitwarden in the terminal:
```
App threw an error during load
Error: The module '/tmp/.org.chromium.Chromium.CPWVNw'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 70. This version of Node.js requires
NODE_MODULE_VERSION 75. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
    at process.func (electron/js2c/asar.js:140:31)
    at process.func [as dlopen] (electron/js2c/asar.js:140:31)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:922:18)
    at Object.func (electron/js2c/asar.js:140:31)
    at Object.func [as .node] (electron/js2c/asar.js:149:18)
    at Module.load (internal/modules/cjs/loader.js:735:32)
    at Module._load (internal/modules/cjs/loader.js:648:12)
    at Module._load (electron/js2c/asar.js:717:26)
    at Function.Module._load (electron/js2c/asar.js:717:26)
    at Module.require (internal/modules/cjs/loader.js:775:19)
A JavaScript error occurred in the main process
Uncaught Exception:
Error: The module '/tmp/.org.chromium.Chromium.CPWVNw'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 70. This version of Node.js requires
NODE_MODULE_VERSION 75. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
    at process.func (electron/js2c/asar.js:140:31)
    at process.func [as dlopen] (electron/js2c/asar.js:140:31)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:922:18)
    at Object.func (electron/js2c/asar.js:140:31)
    at Object.func [as .node] (electron/js2c/asar.js:149:18)
    at Module.load (internal/modules/cjs/loader.js:735:32)
    at Module._load (internal/modules/cjs/loader.js:648:12)
    at Module._load (electron/js2c/asar.js:717:26)
    at Function.Module._load (electron/js2c/asar.js:717:26)
    at Module.require (internal/modules/cjs/loader.js:775:19)
```

**Comment by dctxmei** [comment]
According to the comment:
https://aur.archlinux.org/packages/bitwarden/#comment-715637

This package has been "rebuild" using @lilac:
https://github.com/archlinuxcn/repo/commit/d0cc0ef1c955d39dca30b5ff5d3b81c1b2c7d715

**Comment by lilydjwg** [comment]
@dctxmei you should @lilacbot instead.

**Comment by dctxmei** [comment]
> @dctxmei you should @lilacbot instead.

Thanks for correcting, has changed.

**Comment by dctxmei** [comment]
@floating-cat There were some problems when compiling the package, I was trying to fix it, but for some external factors, it might take 2-3 days.

**Comment by dctxmei** [comment]
There were some errors when compiling with @lilacbot, and I have already manually pushed the package.

**Comment by floating-cat** [comment]
I still can't launch Bitwarden after `pacman -Syyu` and reinstalling Bitwarden. The error message is also the same.
