### ISSUE TITLE
The 'nvchecker==0.4.dev0' distribution was not found 

### ISSUE THREAD

**Issue by colinkeenan** [archlinuxcn/repo#152]
/home/colin %nvchecker my.ini 
Traceback (most recent call last):
  File "/usr/bin/nvchecker", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python3.5/site-packages/pkg_resources/__init__.py", line 3084, in <module>
    @_call_aside
  File "/usr/lib/python3.5/site-packages/pkg_resources/__init__.py", line 3070, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python3.5/site-packages/pkg_resources/__init__.py", line 3097, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python3.5/site-packages/pkg_resources/__init__.py", line 651, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python3.5/site-packages/pkg_resources/__init__.py", line 952, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3.5/site-packages/pkg_resources/__init__.py", line 839, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'nvchecker==0.4.dev0' distribution was not found and is required by the application

**Comment by lilydjwg** [comment]
It needs a rebuild due to the Python upgrade.

**Comment by zsrkmyn** [comment]
Done. Thanks for your reporting.
