### ISSUE TITLE
joplin: broken package

### ISSUE THREAD

**Issue by DuckSoft** [archlinuxcn/repo#1617]
### 问题类型 / Type of issues

* 打包错误 / packaging error

### 受影响的软件包 / Affected packages

* joplin

----
```
❰ducksoft❙~❱✔≻ joplin
internal/modules/cjs/loader.js:638
    throw err;
    ^

Error: Cannot find module '/usr/share/joplin-cli/node_modules/sqlite3/lib/binding/node-v64-linux-x64/node_sqlite3.node'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/usr/share/joplin-cli/node_modules/sqlite3/lib/sqlite3.js:4:15)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
```

**Comment by imlonghao** [comment]
```
Repository      : archlinuxcn
Name            : joplin
Version         : 1.0.201-1.1
Description     : A note taking and to-do application with synchronization
                  capabilities
Architecture    : x86_64
URL             : https://joplinapp.org/
Licenses        : MIT
Groups          : None
Provides        : None
Depends On      : gtk3  libexif  libgsf  libjpeg-turbo  libwebp  libxss  nodejs
                  nss  orc
Optional Deps   : libappindicator-gtk3: for tray icon
Conflicts With  : None
Replaces        : None
Download Size   : 96.23 MiB
Installed Size  : 416.98 MiB
Packager        : lilac (on behalf of imlonghao) <github@esd.cc>
Build Date      : Sun May 10 09:19:46 2020
Validated By    : MD5 Sum  SHA-256 Sum  Signature
```
