### ISSUE TITLE
Motrix-git

### ISSUE THREAD

**Issue by abcfy2** [archlinuxcn/repo#1643]
### 问题类型 / Type of issues

* 过期软件包 / out-of-date packages

### 受影响的软件包 / Affected packages

* Motrix-git

----

上游https://motrix.app/ 已经显示版本号为1.5.10，但是在关于那里显示还是1.4.1，应该更新PKGBUILD中的版本号了吧

**Comment by yuyichao** [comment]
pkgver 用下 git describe 就好?

**Comment by abcfy2** [comment]
对，发现改下pkgver就行了，不知道有没有什么自动化的好办法，不用人工盯tag

**Comment by yuyichao** [comment]
... 说的就是自动用 git describe...

**Comment by abcfy2** [comment]
那什么时候会用上呢？这样包应该会自动更新版本了吧？

**Comment by abcfy2** [comment]
那什么时候会用上呢？这样包应该会自动更新版本了吧？

**Comment by imlonghao** [comment]
@hubutui 

使用以下命令更新 pkgver() 时就能用上正确的版本号了

```
git describe --long --tags | sed 's/^v//;s/\([^-]*-g\)/r\1/;s/-/./g'
1.5.12.r4.g8df97b8
```

另外就是在 https://github.com/archlinuxcn/repo/blob/master/archlinuxcn/motrix-git/PKGBUILD#L59 这里会用到一个版本号，应该也就是这里提到的「关于」里面显示的版本号，看看怎么改合适？

**Comment by hubutui** [comment]
@imlonghao 谢谢。不过“关于”中的版本号不是PKGBUILD文件里写的，应该是上游源码的问题，请跟上游反馈。

**Comment by abcfy2** [comment]
并不是，改了pkgver之后，关于的版本号也会随之改变

**Comment by hubutui** [comment]
@abcfy2 我刚刚测试过的。你可以直接用我刚提交的 PKGBUILD 打包测试一下看看。

**Comment by abcfy2** [comment]
更新新版本之后，启动就报错了:

![截图录屏_electron_20200526090502](https://user-images.githubusercontent.com/5327677/82850728-15ba5100-9f30-11ea-8e59-c9649e04a699.png)

终端错误输出如下:

```
09:04:43.425 › [Motrix] Engine pid: 8321
09:04:43.427 › [Motrix] main engine client connect { host: '127.0.0.1', port: 16800, secret: '' }
09:04:43.487 › [Motrix] Uncaught exception: App version is not a valid semver version: "v1.5.13.r0.g402185e"
09:04:43.488 › Error: App version is not a valid semver version: "v1.5.13.r0.g402185e"
    at newError (/usr/lib/motrix/app/node_modules/builder-util-runtime/out/index.js:212:17)
    at new AppUpdater (/usr/lib/motrix/app/node_modules/electron-updater/out/AppUpdater.js:236:48)
    at new BaseUpdater (/usr/lib/motrix/app/node_modules/electron-updater/out/BaseUpdater.js:20:5)
    at new AppImageUpdater (/usr/lib/motrix/app/node_modules/electron-updater/out/AppImageUpdater.js:78:5)
    at doLoadAutoUpdater (/usr/lib/motrix/app/node_modules/electron-updater/out/main.js:133:20)
    at Object.get [as autoUpdater] (/usr/lib/motrix/app/node_modules/electron-updater/out/main.js:142:28)
    at new a (/usr/lib/motrix/app/electron/main.js:1:164032)
    at m.value (/usr/lib/motrix/app/electron/main.js:1:197364)
    at m.value (/usr/lib/motrix/app/electron/main.js:1:187347)
    at new m (/usr/lib/motrix/app/electron/main.js:1:186837)
09:05:07.759 › [Motrix] UPnPManager map 21301 failed, error:  Error: UPnP port mapping failed
    at /usr/lib/motrix/app/node_modules/nat-api/index.js:226:25
    at /usr/lib/motrix/app/node_modules/nat-api/index.js:324:16
    at /usr/lib/motrix/app/node_modules/nat-api/lib/upnp/index.js:24:23
    at Timeout._onTimeout (/usr/lib/motrix/app/node_modules/nat-api/lib/upnp/index.js:193:7)
    at listOnTimeout (internal/timers.js:531:17)
    at processTimers (internal/timers.js:475:7)
(node:8267) DeprecationWarning: file property is deprecated and will be removed in v5.
(node:8267) DeprecationWarning: file property is deprecated and will be removed in v5.
09:05:07.762 › [Motrix] Engine started
09:05:07.763 › [Motrix] UPnPManager map 26701 failed, error:  Error: UPnP port mapping failed
    at /usr/lib/motrix/app/node_modules/nat-api/index.js:226:25
    at /usr/lib/motrix/app/node_modules/nat-api/index.js:324:16
    at /usr/lib/motrix/app/node_modules/nat-api/lib/upnp/index.js:24:23
    at Timeout._onTimeout (/usr/lib/motrix/app/node_modules/nat-api/lib/upnp/index.js:193:7)
    at listOnTimeout (internal/timers.js:531:17)
    at processTimers (internal/timers.js:475:7)
09:05:07.785 › [Motrix] start UPnP mapping fail UPnP port mapping failed
```

**Comment by hubutui** [comment]
This issue should be fix by https://github.com/archlinuxcn/repo/commit/99e0ff7705b2e352ac99105779beecdaee5f3ca4.
