### ISSUE TITLE
vim-youcompleteme-git 报错

### ISSUE THREAD

**Issue by knight42** [archlinuxcn/repo#205]
vim 启动时的报错信息如下:
```
Error detected while processing function youcompleteme#Enable[10]..<SNR>84_SetUpPython:                                                 
line   34:                                                                                                                              
Traceback (most recent call last):                                                                                                      
Error detected while processing function youcompleteme#Enable[10]..<SNR>84_SetUpPython:                                                 
line   34:                                                                                                                              
  File "<string>", line 15, in <module>                                                                                                 
Error detected while processing function youcompleteme#Enable[10]..<SNR>84_SetUpPython:                                                 
line   34:                                                                                                                              
  File "/usr/share/vim/vimfiles/autoload/../third_party/ycmd/ycmd/utils.py", line 22, in <module>                                       
Error detected while processing function youcompleteme#Enable[10]..<SNR>84_SetUpPython:                                                 
line   34:                                                                                                                              
    from future import standard_library                                                                                                 
Error detected while processing function youcompleteme#Enable[10]..<SNR>84_SetUpPython:                                                 
line   34:                                                                                                                              
ImportError: No module named future   
```
看起来是缺少 future 模块? 

我的 vim-youcompleteme-git 版本是 1698.e2452b6-1, vim-runtime 的版本是 7.4.1386-1.

不知道是否需要提供其他信息?

**Comment by knight42** [comment]
1700.35f6090-1 版本的 vim-youcompleteme-git 已经没有此问题
