### ISSUE TITLE
Motrix无法添加URL,报错 Failed to fetch

### ISSUE THREAD

**Issue by abcfy2** [archlinuxcn/repo#2065]
### 问题类型 / Type of issues

* 打包错误 / packaging error

### 受影响的软件包 / Affected packages

*  motrix-git
----

请在此补充说明。
Please describe in detail here.

使用`sudo pacman -S motrix-git`安装:

```sh
正在解析依赖关系...
正在查找软件包冲突...

软件包 (1) motrix-git-1.5.15.r63.gd020359-1

全部安装大小：  31.63 MiB

:: 进行安装吗？ [Y/n] 
(1/1) 正在检查密钥环里的密钥                                                                                                   [#############################################################################] 100%
(1/1) 正在检查软件包完整性                                                                                                     [#############################################################################] 100%
(1/1) 正在加载软件包文件                                                                                                       [#############################################################################] 100%
(1/1) 正在检查文件冲突                                                                                                         [#############################################################################] 100%
(1/1) 正在检查可用存储空间                                                                                                     [#############################################################################] 100%
:: 正在处理软件包的变化...
(1/1) 正在安装 motrix-git                                                                                                      [#############################################################################] 100%
:: 正在运行事务后钩子函数...
(1/2) Arming ConditionNeedsUpdate...
(2/2) Updating the desktop file MIME type cache...
```

运行`motrix`启动，添加下载链接的时候总是报错 `Failed to fetch`

![image](https://user-images.githubusercontent.com/5327677/105327948-7eb2af80-5c0a-11eb-9490-7bf5ecc5ec3b.png)

![image](https://user-images.githubusercontent.com/5327677/105327979-85d9bd80-5c0a-11eb-9a27-4fb25495bd95.png)

终端有很多似乎是错误信息:

```sh
[22742:0121/170326.144920:INFO:CONSOLE(1)] "[Motrix] fetch downloading task list fail: TypeError: Failed to fetch", source: file:///usr/lib/motrix/app/dist/electron/index.js (1)
[22742:0121/170326.144957:INFO:CONSOLE(544)] "Uncaught (in promise) TypeError: Failed to fetch", source: /usr/lib/motrix/app/node_modules/vuex/dist/vuex.common.js (544)
[22742:0121/170327.145757:INFO:CONSOLE(0)] "Uncaught (in promise) TypeError: Failed to fetch", source: file:///usr/lib/motrix/app/dist/electron/index.html#/task/active (0)
[22742:0121/170327.145828:INFO:CONSOLE(1)] "[Motrix] fetch downloading task list fail: TypeError: Failed to fetch", source: file:///usr/lib/motrix/app/dist/electron/index.js (1)
[22742:0121/170327.145858:INFO:CONSOLE(544)] "Uncaught (in promise) TypeError: Failed to fetch", source: /usr/lib/motrix/app/node_modules/vuex/dist/vuex.common.js (544)
[22742:0121/170328.146571:INFO:CONSOLE(0)] "Uncaught (in promise) TypeError: Failed to fetch", source: file:///usr/lib/motrix/app/dist/electron/index.html#/task/active (0)
[22742:0121/170328.146672:INFO:CONSOLE(1)] "[Motrix] fetch downloading task list fail: TypeError: Failed to fetch", source: file:///usr/lib/motrix/app/dist/electron/index.js (1)
[22742:0121/170328.146712:INFO:CONSOLE(544)] "Uncaught (in promise) TypeError: Failed to fetch", source: /usr/lib/motrix/app/node_modules/vuex/dist/vuex.common.js (544)
[22742:0121/170329.147444:INFO:CONSOLE(0)] "Uncaught (in promise) TypeError: Failed to fetch", source: file:///usr/lib/motrix/app/dist/electron/index.html#/task/active (0)
[22742:0121/170329.147538:INFO:CONSOLE(1)] "[Motrix] fetch downloading task list fail: TypeError: Failed to fetch", source: file:///usr/lib/motrix/app/dist/electron/index.js (1)
[22742:0121/170329.147596:INFO:CONSOLE(544)] "Uncaught (in promise) TypeError: Failed to fetch", source: /usr/lib/motrix/app/node_modules/vuex/dist/vuex.common.js (544)
[22742:0121/170330.148270:INFO:CONSOLE(0)] "Uncaught (in promise) TypeError: Failed to fetch", source: file:///usr/lib/motrix/app/dist/electron/index.html#/task/active (0)
[22742:0121/170330.148361:INFO:CONSOLE(1)] "[Motrix] fetch downloading task list fail: TypeError: Failed to fetch", source: file:///usr/lib/motrix/app/dist/electron/index.js (1)
[22742:0121/170330.148408:INFO:CONSOLE(544)] "Uncaught (in promise) TypeError: Failed to fetch", source: /usr/lib/motrix/app/node_modules/vuex/dist/vuex.common.js (544)
[22742:0121/170331.149141:INFO:CONSOLE(0)] "Uncaught (in promise) TypeError: Failed to fetch", source: file:///usr/lib/motrix/app/dist/electron/index.html#/task/active (0)
[22742:0121/170331.149241:INFO:CONSOLE(1)] "[Motrix] fetch downloading task list fail: TypeError: Failed to fetch", source: file:///usr/lib/motrix/app/dist/electron/index.js (1)
[22742:0121/170331.149279:INFO:CONSOLE(544)] "Uncaught (in promise) TypeError: Failed to fetch", source: /usr/lib/motrix/app/node_modules/vuex/dist/vuex.common.js (544)
[22742:0121/170332.150070:INFO:CONSOLE(0)] "Uncaught (in promise) TypeError: Failed to fetch", source: file:///usr/lib/motrix/app/dist/electron/index.html#/task/active (0)
[22742:0121/170332.150187:INFO:CONSOLE(1)] "[Motrix] fetch downloading task list fail: TypeError: Failed to fetch", source: file:///usr/lib/motrix/app/dist/electron/index.js (1)
[22742:0121/170332.150224:INFO:CONSOLE(544)] "Uncaught (in promise) TypeError: Failed to fetch", source: /usr/lib/motrix/app/node_modules/vuex/dist/vuex.common.js (544)
[22742:0121/170333.151059:INFO:CONSOLE(0)] "Uncaught (in promise) TypeError: Failed to fetch", source: file:///usr/lib/motrix/app/dist/electron/index.html#/task/active (0)
[22742:0121/170333.151147:INFO:CONSOLE(1)] "[Motrix] fetch downloading task list fail: TypeError: Failed to fetch", source: file:///usr/lib/motrix/app/dist/electron/index.js (1)
[22742:0121/170333.151180:INFO:CONSOLE(544)] "Uncaught (in promise) TypeError: Failed to fetch", source: /usr/lib/motrix/app/node_modules/vuex/dist/vuex.common.js (544)
[22742:0121/170334.151801:INFO:CONSOLE(0)] "Uncaught (in promise) TypeError: Failed to fetch", source: file:///usr/lib/motrix/app/dist/electron/index.html#/task/active (0)
[22742:0121/170334.151922:INFO:CONSOLE(1)] "[Motrix] fetch downloading task list fail: TypeError: Failed to fetch", source: file:///usr/lib/motrix/app/dist/electron/index.js (1)
[22742:0121/170334.151945:INFO:CONSOLE(544)] "Uncaught (in promise) TypeError: Failed to fetch", source: /usr/lib/motrix/app/node_modules/vuex/dist/vuex.common.js (544)
[22742:0121/170335.152643:INFO:CONSOLE(0)] "Uncaught (in promise) TypeError: Failed to fetch", source: file:///usr/lib/motrix/app/dist/electron/index.html#/task/active (0)
[22742:0121/170335.152768:INFO:CONSOLE(1)] "[Motrix] fetch downloading task list fail: TypeError: Failed to fetch", source: file:///usr/lib/motrix/app/dist/electron/index.js (1)
[22742:0121/170335.152798:INFO:CONSOLE(544)] "Uncaught (in promise) TypeError: Failed to fetch", source: /usr/lib/motrix/app/node_modules/vuex/dist/vuex.common.js (544)
[22742:0121/170336.153571:INFO:CONSOLE(0)] "Uncaught (in promise) TypeError: Failed to fetch", source: file:///usr/lib/motrix/app/dist/electron/index.html#/task/active (0)
[22742:0121/170336.153688:INFO:CONSOLE(1)] "[Motrix] fetch downloading task list fail: TypeError: Failed to fetch", source: file:///usr/lib/motrix/app/dist/electron/index.js (1)
[22742:0121/170336.153718:INFO:CONSOLE(544)] "Uncaught (in promise) TypeError: Failed to fetch", source: /usr/lib/motrix/app/node_modules/vuex/dist/vuex.common.js (544)
[22742:0121/170337.154497:INFO:CONSOLE(0)] "Uncaught (in promise) TypeError: Failed to fetch", source: file:///usr/lib/motrix/app/dist/electron/index.html#/task/active (0)
[22742:0121/170337.154642:INFO:CONSOLE(1)] "[Motrix] fetch downloading task list fail: TypeError: Failed to fetch", source: file:///usr/lib/motrix/app/dist/electron/index.js (1)
[22742:0121/170337.154668:INFO:CONSOLE(544)] "Uncaught (in promise) TypeError: Failed to fetch", source: /usr/lib/motrix/app/node_modules/vuex/dist/vuex.common.js (544)
[22742:0121/170338.155307:INFO:CONSOLE(0)] "Uncaught (in promise) TypeError: Failed to fetch", source: file:///usr/lib/motrix/app/dist/electron/index.html#/task/active (0)
[22742:0121/170338.155459:INFO:CONSOLE(1)] "[Motrix] fetch downloading task list fail: TypeError: Failed to fetch", source: file:///usr/lib/motrix/app/dist/electron/index.js (1)
[22742:0121/170338.155491:INFO:CONSOLE(544)] "Uncaught (in promise) TypeError: Failed to fetch", source: /usr/lib/motrix/app/node_modules/vuex/dist/vuex.common.js (544)
[22742:0121/170339.156192:INFO:CONSOLE(0)] "Uncaught (in promise) TypeError: Failed to fetch", source: file:///usr/lib/motrix/app/dist/electron/index.html#/task/active (0)
[22742:0121/170339.156335:INFO:CONSOLE(1)] "[Motrix] fetch downloading task list fail: TypeError: Failed to fetch", source: file:///usr/lib/motrix/app/dist/electron/index.js (1)
[22742:0121/170339.156365:INFO:CONSOLE(544)] "Uncaught (in promise) TypeError: Failed to fetch", source: /usr/lib/motrix/app/node_modules/vuex/dist/vuex.common.js (544)
[22742:0121/170340.157037:INFO:CONSOLE(0)] "Uncaught (in promise) TypeError: Failed to fetch", source: file:///usr/lib/motrix/app/dist/electron/index.html#/task/active (0)
[22742:0121/170340.157183:INFO:CONSOLE(1)] "[Motrix] fetch downloading task list fail: TypeError: Failed to fetch", source: file:///usr/lib/motrix/app/dist/electron/index.js (1)
[22742:0121/170340.157212:INFO:CONSOLE(544)] "Uncaught (in promise) TypeError: Failed to fetch", source: /usr/lib/motrix/app/node_modules/vuex/dist/vuex.common.js (544)
```

然而官方原版的AppImage则无此问题。

退出的时候也有报错 `Error: Cannot stop process that is not running.`:

```sh
17:04:59.312 › [Motrix] UPnPManager port unmapping:  23451
17:04:59.312 › [Motrix] UPnPManager port unmapping:  26701
17:04:59.313 › [Motrix] call client fail: request to http://127.0.0.1:16800/jsonrpc failed, reason: connect ECONNREFUSED 127.0.0.1:16800
17:04:59.317 › [Motrix] Engine stopping
17:04:59.317 › [Motrix] Uncaught exception: Cannot stop process that is not running.
17:04:59.317 › Error: Cannot stop process that is not running.
    at /usr/lib/motrix/app/node_modules/forever-monitor/lib/forever-monitor/monitor.js:360:26
    at processTicksAndRejections (internal/process/task_queues.js:79:11)
```

这个问题我记得以前是没有的

**Comment by abcfy2** [comment]
似乎是启动参数有问题:

```sh
Exception: [AbstractOptionHandler.cc:69] errorCode=28 We encountered a problem while processing the option '--max-connection-per-server'.
  -> [OptionHandlerImpl.cc:184] errorCode=1 max-connection-per-server must be between 1 and 16.
```

**Comment by hubutui** [comment]
这个错误请报告给上游，而不是这里．这不是打包的问题．

**Comment by abcfy2** [comment]
我已经确认了，这个问题可以说是打包问题也可以说不是。上游是自己编译了一个aria2c,而这里是将aria2c -> /usr/bin/aria2c.上游使用的aria2c应该是魔改版本，支持这个参数超过16.

解决方案就是把服务器连接数从默认的64改为16就行了
