### ISSUE TITLE
archlinuxcn/python-pandas-profiling fail to run

### ISSUE THREAD

**Issue by CamuseCao** [archlinuxcn/repo#2102]
### 问题类型 / Type of issues

* 打包错误 / packaging error

### 受影响的软件包 / Affected packages

*  archlinuxcn/python-pandas-profiling

----

run `import  pandas_profiling`  get those error
```
Traceback (most recent call last):
  File "./new.py", line 10, in <module>
    import pandas_profiling
  File "/usr/lib/python3.9/site-packages/pandas_profiling/__init__.py", line 7, in <module>
    from pandas_profiling.controller import pandas_decorator
  File "/usr/lib/python3.9/site-packages/pandas_profiling/controller/pandas_decorator.py", line 4, in <module>
    from pandas_profiling.profile_report import ProfileReport
  File "/usr/lib/python3.9/site-packages/pandas_profiling/profile_report.py", line 11, in <module>
    from pandas_profiling.model.describe import describe as describe_df
  File "/usr/lib/python3.9/site-packages/pandas_profiling/model/describe.py", line 10, in <module>
    from pandas_profiling.model.correlations import calculate_correlation
  File "/usr/lib/python3.9/site-packages/pandas_profiling/model/correlations.py", line 12, in <module>
    from pandas_profiling.model.typeset import Boolean, Categorical, Numeric, Unsupported
  File "/usr/lib/python3.9/site-packages/pandas_profiling/model/typeset.py", line 10, in <module>
    from visions.utils import nullable_series_contains
ImportError: cannot import name 'nullable_series_contains' from 'visions.utils' (/usr/lib/python3.9/site-packages/visions/utils/__init__.py)
```

However,  `pandas_profiling` works when I install it with `pip install pandas_profiling`.

PS: `python-multimethod` may be its dependence.

**Comment by CamuseCao** [comment]
After install `python-pywavelets`, problem solved!

**Comment by hubutui** [comment]
are you sure `python-pywavelets` installed fix this?

`python-multimethod` is dep of `python-visions`, I'll update `python-visions`.

**Comment by CamuseCao** [comment]
It did work for me. However, it may not be the whole truth. To figure out more, I try those in my machine.

First, remove `~/.local/lib` with
```
mv ~/.local/lib ~/.local/lib.bak
```
to prevent local packages influence the result.

And remove pacman package `python-pywavelets` with
```pacman -Rnsc python-pywavelets```

Then run `py.py` which only contains
```
import pandas_profiling
```
It fails with the error I report before.

Next I install `pandas_profiling` with 
```
pip install pandas_profiling
```
The output is
```
 pip install pandas_profiling
Defaulting to user installation because normal site-packages is not writeable
Looking in indexes: https://opentuna.cn/pypi/web/simple
Requirement already satisfied: pandas_profiling in /usr/lib/python3.9/site-packages (2.10.1)
Requirement already satisfied: joblib in /usr/lib/python3.9/site-packages (from pandas_profiling) (1.0.0)
Requirement already satisfied: scipy>=1.4.1 in /usr/lib/python3.9/site-packages (from pandas_profiling) (1.6.1)
Requirement already satisfied: pandas!=1.0.0,!=1.0.1,!=1.0.2,!=1.1.0,>=0.25.3 in /usr/lib/python3.9/site-packages (from pandas_profiling) (1.2.2)
Requirement already satisfied: matplotlib>=3.2.0 in /usr/lib/python3.9/site-packages (from pandas_profiling) (3.3.4)
Requirement already satisfied: confuse>=1.0.0 in /usr/lib/python3.9/site-packages (from pandas_profiling) (1.4.0)
Requirement already satisfied: jinja2>=2.11.1 in /usr/lib/python3.9/site-packages (from pandas_profiling) (2.11.3)
Requirement already satisfied: numpy>=1.16.0 in /usr/lib/python3.9/site-packages (from pandas_profiling) (1.20.0)
Requirement already satisfied: attrs>=19.3.0 in /usr/lib/python3.9/site-packages (from pandas_profiling) (20.3.0)
Requirement already satisfied: htmlmin>=0.1.12 in /usr/lib/python3.9/site-packages (from pandas_profiling) (0.1.12)
Requirement already satisfied: missingno>=0.4.2 in /usr/lib/python3.9/site-packages (from pandas_profiling) (0.4.2)
Requirement already satisfied: tangled-up-in-unicode>=0.0.6 in /usr/lib/python3.9/site-packages (from pandas_profiling) (0.0.6)
Requirement already satisfied: requests>=2.24.0 in /usr/lib/python3.9/site-packages (from pandas_profiling) (2.25.1)
Requirement already satisfied: tqdm>=4.48.2 in /usr/lib/python3.9/site-packages (from pandas_profiling) (4.57.0)
Requirement already satisfied: ipywidgets>=7.5.1 in /usr/lib/python3.9/site-packages (from pandas_profiling) (7.6.2)
Requirement already satisfied: seaborn>=0.10.1 in /usr/lib/python3.9/site-packages (from pandas_profiling) (0.11.0)
Requirement already satisfied: pyyaml in /usr/lib/python3.9/site-packages (from confuse>=1.0.0->pandas_profiling) (5.3.1)
Requirement already satisfied: MarkupSafe>=0.23 in /usr/lib/python3.9/site-packages (from jinja2>=2.11.1->pandas_profiling) (1.1.1)
Requirement already satisfied: cycler>=0.10 in /usr/lib/python3.9/site-packages (from matplotlib>=3.2.0->pandas_profiling) (0.10.0)
Requirement already satisfied: kiwisolver>=1.0.1 in /usr/lib/python3.9/site-packages (from matplotlib>=3.2.0->pandas_profiling) (1.3.1)
Requirement already satisfied: numpy>=1.16.0 in /usr/lib/python3.9/site-packages (from pandas_profiling) (1.20.0)
Requirement already satisfied: pillow>=6.2.0 in /usr/lib/python3.9/site-packages (from matplotlib>=3.2.0->pandas_profiling) (8.1.0)
Requirement already satisfied: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.3 in /usr/lib/python3.9/site-packages (from matplotlib>=3.2.0->pandas_profiling) (2.4.7)
Requirement already satisfied: python-dateutil>=2.1 in /usr/lib/python3.9/site-packages (from matplotlib>=3.2.0->pandas_profiling) (2.8.1)
Requirement already satisfied: six in /usr/lib/python3.9/site-packages (from cycler>=0.10->matplotlib>=3.2.0->pandas_profiling) (1.15.0)
Requirement already satisfied: numpy>=1.16.0 in /usr/lib/python3.9/site-packages (from pandas_profiling) (1.20.0)
Requirement already satisfied: matplotlib>=3.2.0 in /usr/lib/python3.9/site-packages (from pandas_profiling) (3.3.4)
Requirement already satisfied: scipy>=1.4.1 in /usr/lib/python3.9/site-packages (from pandas_profiling) (1.6.1)
Requirement already satisfied: seaborn>=0.10.1 in /usr/lib/python3.9/site-packages (from pandas_profiling) (0.11.0)
Requirement already satisfied: python-dateutil>=2.1 in /usr/lib/python3.9/site-packages (from matplotlib>=3.2.0->pandas_profiling) (2.8.1)
Requirement already satisfied: pytz>=2017.3 in /usr/lib/python3.9/site-packages (from pandas!=1.0.0,!=1.0.1,!=1.0.2,!=1.1.0,>=0.25.3->pandas_profiling) (2021.1)
Requirement already satisfied: numpy>=1.16.0 in /usr/lib/python3.9/site-packages (from pandas_profiling) (1.20.0)
Collecting phik>=0.10.0
  Using cached https://opentuna.cn/pypi/web/packages/d9/27/d4197ed93c26d9eeedb7c73c0f24462a65c617807c3140e012950c35ccf9/phik-0.11.0.tar.gz (594 kB)
Requirement already satisfied: numpy>=1.16.0 in /usr/lib/python3.9/site-packages (from pandas_profiling) (1.20.0)
Requirement already satisfied: scipy>=1.4.1 in /usr/lib/python3.9/site-packages (from pandas_profiling) (1.6.1)
Requirement already satisfied: pandas!=1.0.0,!=1.0.1,!=1.0.2,!=1.1.0,>=0.25.3 in /usr/lib/python3.9/site-packages (from pandas_profiling) (1.2.2)
Requirement already satisfied: matplotlib>=3.2.0 in /usr/lib/python3.9/site-packages (from pandas_profiling) (3.3.4)
Requirement already satisfied: numba>=0.38.1 in /usr/lib/python3.9/site-packages (from phik>=0.10.0->pandas_profiling) (0.53.0rc1)
Requirement already satisfied: joblib in /usr/lib/python3.9/site-packages (from pandas_profiling) (1.0.0)
Requirement already satisfied: llvmlite<0.37,>=0.36.0rc1 in /usr/lib/python3.9/site-packages (from numba>=0.38.1->phik>=0.10.0->pandas_profiling) (0.36.0rc1)
Requirement already satisfied: numpy>=1.16.0 in /usr/lib/python3.9/site-packages (from pandas_profiling) (1.20.0)
Requirement already satisfied: setuptools in /usr/lib/python3.9/site-packages (from numba>=0.38.1->phik>=0.10.0->pandas_profiling) (53.0.0)
Requirement already satisfied: six in /usr/lib/python3.9/site-packages (from cycler>=0.10->matplotlib>=3.2.0->pandas_profiling) (1.15.0)
Requirement already satisfied: chardet>=3.0.2 in /usr/lib/python3.9/site-packages (from requests>=2.24.0->pandas_profiling) (3.0.4)
Requirement already satisfied: idna>=2.5 in /usr/lib/python3.9/site-packages (from requests>=2.24.0->pandas_profiling) (2.10)
Requirement already satisfied: urllib3>=1.21.1 in /usr/lib/python3.9/site-packages (from requests>=2.24.0->pandas_profiling) (1.26.3)
Requirement already satisfied: numpy>=1.16.0 in /usr/lib/python3.9/site-packages (from pandas_profiling) (1.20.0)
Requirement already satisfied: numpy>=1.16.0 in /usr/lib/python3.9/site-packages (from pandas_profiling) (1.20.0)
Requirement already satisfied: scipy>=1.4.1 in /usr/lib/python3.9/site-packages (from pandas_profiling) (1.6.1)
Requirement already satisfied: pandas!=1.0.0,!=1.0.1,!=1.0.2,!=1.1.0,>=0.25.3 in /usr/lib/python3.9/site-packages (from pandas_profiling) (1.2.2)
Requirement already satisfied: matplotlib>=3.2.0 in /usr/lib/python3.9/site-packages (from pandas_profiling) (3.3.4)
Collecting visions[type_image_path]==0.6.0
  Using cached https://opentuna.cn/pypi/web/packages/98/30/b1e70bc55962239c4c3c9660e892be2d8247a882135a3035c10ff7f02cde/visions-0.6.0-py3-none-any.whl (75 kB)
Requirement already satisfied: tangled-up-in-unicode>=0.0.6 in /usr/lib/python3.9/site-packages (from pandas_profiling) (0.0.6)
Requirement already satisfied: pandas!=1.0.0,!=1.0.1,!=1.0.2,!=1.1.0,>=0.25.3 in /usr/lib/python3.9/site-packages (from pandas_profiling) (1.2.2)
Requirement already satisfied: attrs>=19.3.0 in /usr/lib/python3.9/site-packages (from pandas_profiling) (20.3.0)
Requirement already satisfied: numpy>=1.16.0 in /usr/lib/python3.9/site-packages (from pandas_profiling) (1.20.0)
Requirement already satisfied: networkx>=2.4 in /usr/lib/python3.9/site-packages (from visions[type_image_path]==0.6.0->pandas_profiling) (2.5)
Requirement already satisfied: pillow>=6.2.0 in /usr/lib/python3.9/site-packages (from matplotlib>=3.2.0->pandas_profiling) (8.1.0)
Collecting imagehash
  Using cached https://opentuna.cn/pypi/web/packages/8e/18/9dbb772b5ef73a3069c66bb5bf29b9fb4dd57af0d5790c781c3f559bcca6/ImageHash-4.2.0-py2.py3-none-any.whl (295 kB)
Requirement already satisfied: pillow>=6.2.0 in /usr/lib/python3.9/site-packages (from matplotlib>=3.2.0->pandas_profiling) (8.1.0)
Requirement already satisfied: scipy>=1.4.1 in /usr/lib/python3.9/site-packages (from pandas_profiling) (1.6.1)
Requirement already satisfied: six in /usr/lib/python3.9/site-packages (from cycler>=0.10->matplotlib>=3.2.0->pandas_profiling) (1.15.0)
Requirement already satisfied: numpy>=1.16.0 in /usr/lib/python3.9/site-packages (from pandas_profiling) (1.20.0)
Requirement already satisfied: decorator>=4.3.0 in /usr/lib/python3.9/site-packages (from networkx>=2.4->visions[type_image_path]==0.6.0->pandas_profiling) (4.4.2)
Collecting PyWavelets
  Using cached https://opentuna.cn/pypi/web/packages/d8/4a/5ca7825e9fa554134a8b5176a53bc867569b3eba91f34c384f0c03a88f24/PyWavelets-1.1.1-cp39-cp39-manylinux1_x86_64.whl (4.3 MB)
Requirement already satisfied: numpy>=1.16.0 in /usr/lib/python3.9/site-packages (from pandas_profiling) (1.20.0)
Requirement already satisfied: tangled-up-in-unicode>=0.0.6 in /usr/lib/python3.9/site-packages (from pandas_profiling) (0.0.6)
Requirement already satisfied: pandas!=1.0.0,!=1.0.1,!=1.0.2,!=1.1.0,>=0.25.3 in /usr/lib/python3.9/site-packages (from pandas_profiling) (1.2.2)
Requirement already satisfied: attrs>=19.3.0 in /usr/lib/python3.9/site-packages (from pandas_profiling) (20.3.0)
Requirement already satisfied: numpy>=1.16.0 in /usr/lib/python3.9/site-packages (from pandas_profiling) (1.20.0)
Requirement already satisfied: networkx>=2.4 in /usr/lib/python3.9/site-packages (from visions[type_image_path]==0.6.0->pandas_profiling) (2.5)
Using legacy 'setup.py install' for phik, since package 'wheel' is not installed.
Installing collected packages: PyWavelets, visions, imagehash, phik
    Running setup.py install for phik ... done
Successfully installed PyWavelets-1.1.1 imagehash-4.2.0 phik-0.11.0 visions-0.6.0
```

Now, `py.py` works out of box.

So, pip install `PyWavelets-1.1.1 imagehash-4.2.0 phik-0.11.0 visions-0.6.0` for me.
However, I have already get
```
archlinuxcn/python-visions 0.7.1-1
archlinuxcn/python-imagehash 4.0-3
```

Next, remove local lib again. Then install `archlinuxcn/python-pywavelets 1.1.1-2`. And try to instal `phik` with `pip install phik` due to no pacamn package for it, which throw the error present below
```
pandas-profiling 2.10.1 requires visions[type_image_path]==0.6.0, but you have visions 0.7.1 which is incompatible.
```

Now, I guess `archlinuxcn/python-visions 0.7.1-1` is to blame, its version doesn't meet `pandas-profiling`'s requirement!!! What's more, may be a `python-phik` package is needed to run `python-pandas_profiling` without user install `phik` with pip.

PS: There are many other python packages installed in my machine with pacman. If it's needed, I will provide a list of them.

**Comment by hubutui** [comment]
ok, maybe you could report it to pandas-profiling upstream. ArchLinux will only package the latest release, so `python-visions` is 0.7.1 now. Or you could wait until upstream upgrade dep visions to latest release.

**Comment by CamuseCao** [comment]
Thanks.

**Comment by yan12125** [comment]
After installing python-imagehash and python-pydantic besides python-pandas-profiling, `python -c 'import pandas_profiling'` runs fine. This issue can be closed after adding missing dependencies.
