### ISSUE TITLE
bcc 运行时错误

### ISSUE THREAD

**Issue by condy0919** [archlinuxcn/repo#2538]
### 问题类型 / Type of issues

* 其它 / other

### 受影响的软件包 / Affected packages

* bcc-tools-git

----

因为近期 clang/llvm 升级到了 13，而 bcc 仍依赖 `libclang-cpp.so.12`，因此出现运行时错误。

```
condy@Youmu ~ % sudo bcc execsnoop
[sudo] password for condy:
Traceback (most recent call last):
  File "/usr/share/bcc/tools/execsnoop", line 21, in <module>
    from bcc import BPF
  File "/usr/lib/python3.9/site-packages/bcc/__init__.py", line 26, in <module>
    from .libbcc import lib, bcc_symbol, bcc_symbol_option, bcc_stacktrace_build_id, _SYM_CB_TYPE
  File "/usr/lib/python3.9/site-packages/bcc/libbcc.py", line 17, in <module>
    lib = ct.CDLL("libbcc.so.0", use_errno=True)
  File "/usr/lib/python3.9/ctypes/__init__.py", line 374, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: libclang-cpp.so.12: cannot open shared object file: No such file or directory
```

**Comment by lilydjwg** [comment]
Updated.

**Comment by condy0919** [comment]
经验证，已修复
