### ISSUE TITLE
python-torchvision should be rebuilt against newer python-pytorch

### ISSUE THREAD

**Issue by yan12125** [archlinuxcn/repo#2564]
### 问题类型 / Type of issues

* 打包错误 / packaging error

### 受影响的软件包 / Affected packages

* python-torchvision

----

```
$ python -c 'import torchvision.ops; torchvision.ops.nms(0, 0, 0)'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/lib/python3.9/site-packages/torchvision/ops/boxes.py", line 34, in nms
    _assert_has_ops()
  File "/usr/lib/python3.9/site-packages/torchvision/extension.py", line 27, in _assert_has_ops
    raise RuntimeError(
RuntimeError: Couldn't load custom C++ ops. This can happen if your PyTorch and torchvision versions are incompatible, or if you had errors while compiling torchvision from source. For further information on the compatible versions, check https://github.com/pytorch/vision#installation for the compatibility matrix. Please check your PyTorch version with torch.__version__ and your torchvision version with torchvision.__version__ and verify if they are compatible, and if not please reinstall torchvision so that it matches your PyTorch install.
```

The actual error is clear with the following changes:

```diff
--- /usr/lib/python3.9/site-packages/torchvision/extension.py   2021-10-22 06:26:15.000000000 +0800
+++ /usr/lib/python3.9/site-packages/torchvision/extension.py.new       2021-11-24 16:52:28.995048702 +0800
@@ -18,7 +18,8 @@
     def _has_ops():  # noqa: F811
         return True
 except (ImportError, OSError):
-    pass
+    import traceback
+    traceback.print_exc()
```

The result is:

```
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/torchvision/extension.py", line 15, in <module>
    torch.ops.load_library(lib_path)
  File "/usr/lib/python3.9/site-packages/torch/_ops.py", line 110, in load_library
    ctypes.CDLL(path)
  File "/usr/lib/python3.9/ctypes/__init__.py", line 374, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /usr/lib/python3.9/site-packages/torchvision/_C.so: undefined symbol: _ZNK2at6Tensor7reshapeEN3c108ArrayRefIlEE
```

Please also consider commenting out the check() function from PKGBUILD. If you don't plan to keep tests green, don't run them as they waste time of AUR package users.

**Comment by yan12125** [comment]
Thanks for the update. However, this package is not actually rebuilt (see https://build.archlinuxcn.org/packages/#/python-torchvision). If I understand lilac correctly, a package is rebuilt if (1) at least an entry in `update_on` changes (2) PKGBUILD & related files change _when the last build fails_ (3) pkgrel changes - see https://github.com/archlinuxcn/lilac/blob/e6cc6208559b8590cdef1d3549b6f6f97e5835fd/lilac#L394-L402
