### ISSUE TITLE
jdownloader2 文件不区分大小写重复

### ISSUE THREAD

**Issue by holymonson** [archlinuxcn/repo#2744]
### 问题类型 / Type of issues

* 其它 / other

### 受影响的软件包 / Affected packages

* jdownloader2
* 整个`archlinuxcn`仓库

----

`jdownloader2`文件夹下包含`jdownloader`和`JDownloader`两个文件，在不区分大小写的文件系统下，会导致整个`archlinuxcn`仓库都没法checkout。
`jdownloader`这个文件完全可以用symlink代替。

**Comment by oldherl** [comment]
正常来说，linux不应使用不区分大小写的文件系统。

**Comment by holymonson** [comment]
我看了下，PKGBUILD里根本就没有用`jdownloader`这个文件，用`ln -s`代替了，所以就没必要留着这个文件了？

**Comment by yan12125** [comment]
> 正常来说，linux不应使用不区分大小写的文件系统。

Yes, but this issue is still valid as the repository may be cloned on case-insensitive filesystems. See https://github.com/archlinuxcn/repo/pull/1096 and https://aur.archlinux.org/packages/jdownloader2#comment-853628.

**Comment by yan12125** [comment]
Seems the current lilac does not allow removing a file downloaded from AUR. If I run rm after `aur_pre_build()`:

```yaml
pre_build_script: |
  aur_pre_build(maintainers=['Derson5'])
  run_cmd(['rm', '-f', 'jdownloader'])

post_build: aur_post_build
```

`aur_post_build()` fails as it cannot find the file `jdownloader`.

```
[D 04-22 20:34:35.815 cmd:88] running ['git', 'add', '-f', '--', 'JDownloader', 'JDownloaderHeadless', 'JDownloaderHeadlessCleanLogin', 'JDownloaderHeadlessCtl', 'PKGBUILD', 'functions.sh', 'jd-container16.png', 'jd-container22.png', 'jd-container24.png', 'jd-container256.png', 'jd-container32.png', 'jd-container48.png', 'jd-containers.desktop', 'jdownloader', 'jdownloader.desktop', 'jdownloader.install', 'jdownloader.service', 'jdownloader.xml', 'jdownloader16.png', 'jdownloader22.png', 'jdownloader24.png', 'jdownloader256.png', 'jdownloader32.png', 'jdownloader48.png'], not using pty, showing output
fatal: pathspec 'jdownloader' did not match any files
[D 04-22 20:34:35.819 cmd:88] running ['git', 'reset', '--', 'JDownloader', 'JDownloaderHeadless', 'JDownloaderHeadlessCleanLogin', 'JDownloaderHeadlessCtl', 'PKGBUILD', 'functions.sh', 'jd-container16.png', 'jd-container22.png', 'jd-container24.png', 'jd-container256.png', 'jd-container32.png', 'jd-container48.png', 'jd-containers.desktop', 'jdownloader', 'jdownloader.desktop', 'jdownloader.install', 'jdownloader.service', 'jdownloader.xml', 'jdownloader16.png', 'jdownloader22.png', 'jdownloader24.png', 'jdownloader256.png', 'jdownloader32.png', 'jdownloader48.png'], not using pty, showing output
Unstaged changes after reset:
M	archlinuxcn/jdownloader2/PKGBUILD
[E 04-22 20:34:35.830 worker:241] build failed
    Traceback (most recent call last):
      File "/usr/lib/python3.10/site-packages/lilac2/worker.py", line 209, in main
        lilac_build(
      File "/usr/lib/python3.10/site-packages/lilac2/worker.py", line 128, in lilac_build
        post_build()
      File "/usr/lib/python3.10/site-packages/lilac2/api.py", line 554, in aur_post_build
        git_add_files(_g.aur_building_files, force=True)
      File "/usr/lib/python3.10/site-packages/lilac2/api.py", line 300, in git_add_files
        _run_cmd(['git', 'add', '-f', '--'] + files)
      File "/usr/lib/python3.10/site-packages/lilac2/cmd.py", line 155, in run_cmd
        raise subprocess.CalledProcessError(code, cmd, output=outs)
    subprocess.CalledProcessError: Command '['git', 'add', '-f', '--', 'JDownloader', 'JDownloaderHeadless', 'JDownloaderHeadlessCleanLogin', 'JDownloaderHeadlessCtl', 'PKGBUILD', 'functions.sh', 'jd-container16.png', 'jd-container22.png', 'jd-container24.png', 'jd-container256.png', 'jd-container32.png', 'jd-container48.png', 'jd-containers.desktop', 'jdownloader', 'jdownloader.desktop', 'jdownloader.install', 'jdownloader.service', 'jdownloader.xml', 'jdownloader16.png', 'jdownloader22.png', 'jdownloader24.png', 'jdownloader256.png', 'jdownloader32.png', 'jdownloader48.png']' returned non-zero exit status 128.
```

Under the hood, `aur_pre_build()` stores the list of files [in a namespace `_g`](https://github.com/archlinuxcn/lilac/blob/c46923cccdf33c0b1b1c5c386d283e9710f984f5/lilac2/api.py#L526), and that namespace cannot be touched by lilac.py or lilac.yaml.

**Comment by lilydjwg** [comment]
lilac.py should be able to access `_g`, imported from either `lilac2.api` or `lilaclib`.

**Comment by yan12125** [comment]
> Maybe I can make aur_post_build only adds existing files.

Thanks! That sounds cleaner than hacking `_g` :)

**Comment by heavysink** [comment]
已merge。谢谢大家！
