### ISSUE TITLE
ruby-solargraph missing dependencies

### ISSUE THREAD

**Issue by Freed-Wu** [archlinuxcn/repo#2946]
### 问题类型 / Type of issues

* 打包错误 / packaging error

### 受影响的软件包 / Affected packages

* （请在此填写包名，每行一个，开头加上星号 / package names, one per line）

ruby-solargraph missing dependencies.

```sh
❯ sudo pacman -S ruby-solargraph
...
❯ solargraph --help
/usr/lib/ruby/3.0.0/rubygems/specification.rb:1453:in `rescue in block in activate_dependencies': Could not find 'diff-lcs' (~> 1.4) among 119 total gem(s) (Gem::MissingSpecError)
Checked in 'GEM_PATH=/home/wzy/.local/share/gem/ruby/3.0.0:/usr/lib/ruby/gems/3.0.0' at: /usr/lib/ruby/gems/3.0.0/specifications/solargraph-0.47.2.gemspec, execute `gem env` for more information
        from /usr/lib/ruby/3.0.0/rubygems/specification.rb:1450:in `block in activate_dependencies'
        from /usr/lib/ruby/3.0.0/rubygems/specification.rb:1439:in `each'
        from /usr/lib/ruby/3.0.0/rubygems/specification.rb:1439:in `activate_dependencies'
        from /usr/lib/ruby/3.0.0/rubygems/specification.rb:1421:in `activate'
        from /usr/lib/ruby/3.0.0/rubygems.rb:286:in `block in activate_bin_path'
        from /usr/lib/ruby/3.0.0/rubygems.rb:285:in `synchronize'
        from /usr/lib/ruby/3.0.0/rubygems.rb:285:in `activate_bin_path'
        from /usr/bin/solargraph:25:in `<main>'
/usr/lib/ruby/3.0.0/rubygems/dependency.rb:311:in `to_specs': Could not find 'diff-lcs' (~> 1.4) among 119 total gem(s) (Gem::MissingSpecError)
Checked in 'GEM_PATH=/home/wzy/.local/share/gem/ruby/3.0.0:/usr/lib/ruby/gems/3.0.0' , execute `gem env` for more information
        from /usr/lib/ruby/3.0.0/rubygems/specification.rb:1451:in `block in activate_dependencies'
        from /usr/lib/ruby/3.0.0/rubygems/specification.rb:1439:in `each'
        from /usr/lib/ruby/3.0.0/rubygems/specification.rb:1439:in `activate_dependencies'
        from /usr/lib/ruby/3.0.0/rubygems/specification.rb:1421:in `activate'
        from /usr/lib/ruby/3.0.0/rubygems.rb:286:in `block in activate_bin_path'
        from /usr/lib/ruby/3.0.0/rubygems.rb:285:in `synchronize'
        from /usr/lib/ruby/3.0.0/rubygems.rb:285:in `activate_bin_path'
        from /usr/bin/solargraph:25:in `<main>'
...
```

----

请在此补充说明。
Please describe in detail here.

miss:

- ruby-diff-lcs
- kramdown
- unicode-dispaly_width

**Comment by a-wing** [comment]
need add:
- [ ] kramdown
- [ ] diff-lcs
  - [ ] hoe
  - [ ] hoe-doofus
  - [ ] hoe-gemspec2
  - [ ] hoe-git
  - [ ] hoe-rubygems

`unicode-dispaly_width` depend ?

**Comment by Freed-Wu** [comment]
```sh
❯ sudo pacman -R ruby-unicode-display_width
checking dependencies...
error: failed to prepare transaction (could not satisfy dependencies)
:: removing ruby-unicode-display_width breaks dependency 'ruby-unicode-display_width' required by ruby-rubocop
:: removing ruby-unicode-display_width breaks dependency 'ruby-unicode-display_width>=1.1.1' required by ruby-terminal-table
  ⇣90.6 KiB/s ⇡763 B/s 192.168.151.188   234 Mbps   0.77   75%   17.3G   0B   23:12:29 
    ~/Downloads    master +5 
❯ sudo pacman -R ruby-rubocop
checking dependencies...
error: failed to prepare transaction (could not satisfy dependencies)
:: removing ruby-rubocop breaks dependency 'ruby-rubocop' required by ruby-solargraph
```

**Comment by SilverRainZ** [comment]
FYI: https://github.com/archlinuxcn/repo/issues/2952#event-7599009413

**Comment by a-wing** [comment]
Sorry, I not used ruby-solargraph for a long time, The quality of this package cannot be guaranteed

**I decision orphaning this package**
