### ISSUE TITLE
Ruby-solargraph is missing dependencies

### ISSUE THREAD

**Issue by Avimitin** [archlinuxcn/repo#2963]
### 问题类型 / Type of issues

* 打包错误 / packaging error

### 受影响的软件包 / Affected packages

* ruby-solargraph

----

We need to add the below packages into depends

* `ruby-kramdown`

    ```text
    /usr/lib/ruby/3.0.0/rubygems/specification.rb:1453:in `rescue in block in activate_dependencies': Could not find 'kramdown' (~> 2.3) among 113 total gem(s) (Gem::MissingSpecError)
    ```

* `ruby-kramdown-parser-gfm`

    ```text
    /usr/lib/ruby/3.0.0/rubygems/specification.rb:1453:in `rescue in block in activate_dependencies': Could not find 'kramdown-parser-gfm' (~> 1.1) among 114 total gem(s) (Gem::MissingSpecError)
    ```
* `ruby-diff-lcs`

    ```text
   "/usr/lib/ruby/3.0.0/rubygems/specification.rb:1453:in `rescue in block in activate_dependencies': Could not find 'kramdown' (~> 2.3) among 113 total gem(s) (Gem::MissingSpecError)
    ```

**Comment by a-wing** [comment]
Duplicate #2946
