### ISSUE TITLE
solaar-git 打包错误导致无法运行

### ISSUE THREAD

**Issue by Y7n05h** [archlinuxcn/repo#3356]
### 问题类型 / Type of issues

* 打包错误 / packaging error

### 受影响的软件包 / Affected packages

* solaar-git

----

```
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/solaar/__init__.py", line 26, in <module>
    __version__ = _subprocess.check_output(['git', 'describe', '--always'], cwd=_sys.path[0],
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['git', 'describe', '--always']' returned non-zero exit status 128.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/solaar/__init__.py", line 30, in <module>
    __version__ = _pkgutil.get_data('solaar', 'commit').strip().decode()
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/pkgutil.py", line 640, in get_data
    return loader.get_data(resource_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap_external>", line 1130, in get_data
FileNotFoundError: [Errno 2] No such file or directory: '/usr/lib/python3.11/site-packages/solaar/commit'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/solaar", line 54, in <module>
    import solaar.gtk
  File "/usr/lib/python3.11/site-packages/solaar/__init__.py", line 32, in <module>
    __version__ = _pkgutil.get_data('solaar', 'version').strip().decode()
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/pkgutil.py", line 640, in get_data
    return loader.get_data(resource_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap_external>", line 1130, in get_data
FileNotFoundError: [Errno 2] No such file or directory: '/usr/lib/python3.11/site-packages/solaar/version'
```

**Comment by heavysink** [comment]
现在应该好了吧？

**Comment by Y7n05h** [comment]
> 现在应该好了吧？

目前存在相同问题。

**Comment by oldherl** [comment]
似乎修好了？
