### ISSUE TITLE
python-dm-tree rebuild is needed

### ISSUE THREAD

**Issue by hubutui** [archlinuxcn/repo#3543]
### 问题类型 / Type of issues

* 打包错误 / packaging error

### 受影响的软件包 / Affected packages

* python-dm-tree

----
```
>>> import tree
Traceback (most recent call last):
  File "<input>", line 1, in <module>
    import tree
  File "/usr/lib/python3.11/site-packages/tree/__init__.py", line 23, in <module>
    from .sequence import _is_attrs
  File "/usr/lib/python3.11/site-packages/tree/sequence.py", line 19, in <module>
    from tree import _tree
  File "/usr/lib/python3.11/site-packages/bpython/curtsiesfrontend/repl.py", line 275, in _create_module
    module_object = self.loader.create_module(spec)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ImportError: /usr/lib/python3.11/site-packages/tree/_tree.cpython-311-x86_64-linux-gnu.so: undefined symbol: _ZN4absl12lts_2023012516raw_log_internal6RawLogENS0_11LogSeverityEPKciS4_z
```

**Comment by hubutui** [comment]
我擦，原来是我自己的包．
