### ISSUE TITLE
python-androguard 运行错误，缺少依赖

### ISSUE THREAD

**Issue by dongfengweixiao** [archlinuxcn/repo#3870]
### 问题类型 / Type of issues

* 其它 / other

### 受影响的软件包 / Affected packages

* python-androguard

----
按 https://androguard.readthedocs.io/en/latest/intro/axml.html#decode-any-other-xml-file 链接给出的文档，执行命令，存在以下错误：

- python-loguru
  ```
  $ androguard axml r/a/a.xml
  Traceback (most recent call last):
    File "/usr/bin/androguard", line 5, in <module>
      from androguard.cli.cli import entry_point
    File "/usr/lib/python3.12/site-packages/androguard/cli/cli.py", line 9, in <module>
      from loguru import logger
  ModuleNotFoundError: No module named 'loguru'
  ```
- python-apkinspector(aur)
  ```
  $ androguard axml r/a/a.xml
  Traceback (most recent call last):
    File "/usr/bin/androguard", line 5, in <module>
      from androguard.cli.cli import entry_point
    File "/usr/lib/python3.12/site-packages/androguard/cli/cli.py", line 11, in <module>
      import androguard.core.apk
    File "/usr/lib/python3.12/site-packages/androguard/core/apk/__init__.py", line 20, in <module>
      from apkInspector.headers import ZipEntry
  ModuleNotFoundError: No module named 'apkInspector'
  ```
- python-oscrypto
  ```
  $ androguard axml r/a/a.xml
  Traceback (most recent call last):
    File "/usr/bin/androguard", line 5, in <module>
      from androguard.cli.cli import entry_point
    File "/usr/lib/python3.12/site-packages/androguard/cli/cli.py", line 13, in <module>
      from androguard.cli.main import (androarsc_main,
    File "/usr/lib/python3.12/site-packages/androguard/cli/main.py", line 14, in <module>
      from oscrypto import asymmetric
  ModuleNotFoundError: No module named 'oscrypto'
  ```
- python-mutf8(aur)
  ```
  $ androguard axml r/a/a.xml
  Traceback (most recent call last):
    File "/usr/bin/androguard", line 5, in <module>
      from androguard.cli.cli import entry_point
    File "/usr/lib/python3.12/site-packages/androguard/cli/cli.py", line 13, in <module>
      from androguard.cli.main import (androarsc_main,
    File "/usr/lib/python3.12/site-packages/androguard/cli/main.py", line 18, in <module>
      from androguard.session import Session
    File "/usr/lib/python3.12/site-packages/androguard/session.py", line 5, in <module>
      from androguard.core.analysis.analysis import Analysis, StringAnalysis
    File "/usr/lib/python3.12/site-packages/androguard/core/analysis/analysis.py", line 14, in <module>
      from androguard.core import bytecode, dex
    File "/usr/lib/python3.12/site-packages/androguard/core/bytecode.py", line 14, in <module>
      from androguard.core.dex.dex_types import Kind, Operand
    File "/usr/lib/python3.12/site-packages/androguard/core/dex/__init__.py", line 28, in <module>
      from androguard.core import mutf8
    File "/usr/lib/python3.12/site-packages/androguard/core/mutf8/__init__.py", line 1, in <module>
      from mutf8 import decode_modified_utf8, encode_modified_utf8
  ModuleNotFoundError: No module named 'mutf8'
  ```
- python-dataset(AUR)
  ```
  $ androguard axml r/a/a.xml
  Traceback (most recent call last):
    File "/usr/bin/androguard", line 5, in <module>
      from androguard.cli.cli import entry_point
    File "/usr/lib/python3.12/site-packages/androguard/cli/cli.py", line 13, in <module>
      from androguard.cli.main import (androarsc_main,
    File "/usr/lib/python3.12/site-packages/androguard/cli/main.py", line 18, in <module>
      from androguard.session import Session
    File "/usr/lib/python3.12/site-packages/androguard/session.py", line 10, in <module>
      import dataset
  ModuleNotFoundError: No module named 'dataset'
  ```
- python-frida(AUR)
  ```
  $ androguard axml r/a/a.xml
  Traceback (most recent call last):
    File "/usr/bin/androguard", line 5, in <module>
      from androguard.cli.cli import entry_point
    File "/usr/lib/python3.12/site-packages/androguard/cli/cli.py", line 13, in <module>
      from androguard.cli.main import (androarsc_main,
    File "/usr/lib/python3.12/site-packages/androguard/cli/main.py", line 24, in <module>
      from androguard.ui import DynamicUI
    File "/usr/lib/python3.12/site-packages/androguard/ui/__init__.py", line 19, in <module>
      from androguard.ui.widget.details import DetailsFrame
    File "/usr/lib/python3.12/site-packages/androguard/ui/widget/details.py", line 12, in <module>
      from androguard.ui.data_types import DisplayTransaction
    File "/usr/lib/python3.12/site-packages/androguard/ui/data_types.py", line 4, in <module>
      from androguard.pentest import Message, MessageEvent, MessageSystem
    File "/usr/lib/python3.12/site-packages/androguard/pentest/__init__.py", line 3, in <module>
      import frida
  ModuleNotFoundError: No module named 'frida'
  ```

暂时只排除到这些依赖，其中 python-frida（aur）无法编译为 Arch Linux 下的安装包（同时验证了本地编译和 GitHub action 编译）。

**Comment by Integral-Tech** [comment]
I have added the following packages into archlinuxcn, but ```python-frida``` failed to build.
The ```depends``` field of ```python-androguard``` has been updated.

**Comment by oldherl** [comment]
[archlinuxcn] should not contain a package that have a (non-optional) dependency outside of [core], [extra] and [archlinuxcn].

**Comment by oldherl** [comment]
这是因为 python-frida 包的打包脚本中有在隔离环境下无法正常运行的命令，需要修正。在修正以前，应先将 python-androguard 从 [archlinuxcn] 中移除

**Comment by Integral-Tech** [comment]
已从 [archlinuxcn] 仓库中移除 ```python-frida``` 和 ```python-androguard```
https://github.com/archlinuxcn/repo/commit/5883b22ac4ce0212540ad05d14be0e463695d166
https://github.com/archlinuxcn/repo/commit/82cd64e4512f367a6765e01324fa2d7554bd504c
