### ISSUE TITLE
rstudio-desktop-bin not finding dependency gstreamer0.10-base

### ISSUE THREAD

**Issue by xgdgsc** [archlinuxcn/repo#397]
I don' t know why it still cannot find the dependency after I  added the package  gstreamer0.10-base.
```
命令执行失败！

命令 ['extra-x86_64-build', '--', '--', '--holdver'] 返回了错误号 255。命令的输出如下：

:: Synchronizing package databases...
 core is up to date
 extra is up to date
 community is up to date
:: Starting full system upgrade...
 there is nothing to do
 [1m [32m==> (B [m [1m Building in chroot for [extra] (x86_64)... (B [m
 [1m [32m==> (B [m [1m Creating clean working copy [lilydjwg]... (B [m [1mdone (B [m
 [1m [32m==> (B [m [1m Making package: rstudio-desktop-bin 1.0.143-2 (Fri Apr 28 17:36:27 CST 2017) (B [m
 [1m [32m==> (B [m [1m Retrieving sources... (B [m
 [1m [34m  -> (B [m [1m Found rstudio-1.0.143-amd64.deb (B [m
 [1m [32m==> (B [m [1m Validating source files with md5sums... (B [m
    rstudio-1.0.143-amd64.deb ... Passed
 [1m [32m==> (B [m [1m Making package: rstudio-desktop-bin 1.0.143-2 (Fri Apr 28 17:36:28 CST 2017) (B [m
 [1m [32m==> (B [m [1m Checking runtime dependencies... (B [m
 [1m [32m==> (B [m [1m Installing missing dependencies... (B [m
error: target not found: gstreamer0.10-base
 [1m [31m==> ERROR: (B [m [1m 'pacman' failed to install missing dependencies. (B [m
 [1m [31m==> ERROR: (B [m [1m Build failed, check /var/lib/archbuild/extra-x86_64/lilydjwg/build (B [m

调用栈如下：

Traceback (most recent call last):
  File "/home/lilydjwg/soft/lilac/lilac", line 164, in build_package
    depends = DEPENDS.get(package, ()),
  File "/home/lilydjwg/soft/lilac/lilaclib.py", line 428, in lilac_build
    call_build_cmd(build_prefix, depend_packages, pkgs_to_build)
  File "/home/lilydjwg/soft/lilac/lilaclib.py", line 458, in call_build_cmd
    build_output = run_cmd(cmd, use_pty=True)
  File "/home/lilydjwg/soft/lilac/lilaclib.py", line 530, in run_cmd
    raise CalledProcessError(code, cmd, out)
subprocess.CalledProcessError: Command '['extra-x86_64-build', '--', '--', '--holdver']' returned non-zero exit status 255.命令执行失败！

命令 ['extra-x86_64-build', '--', '--', '--holdver'] 返回了错误号 255。命令的输出如下：

:: Synchronizing package databases...
 core is up to date
 extra is up to date
 community is up to date
:: Starting full system upgrade...
 there is nothing to do
 [1m [32m==> (B [m [1m Building in chroot for [extra] (x86_64)... (B [m
 [1m [32m==> (B [m [1m Creating clean working copy [lilydjwg]... (B [m [1mdone (B [m
 [1m [32m==> (B [m [1m Making package: rstudio-desktop-bin 1.0.143-2 (Fri Apr 28 17:36:27 CST 2017) (B [m
 [1m [32m==> (B [m [1m Retrieving sources... (B [m
 [1m [34m  -> (B [m [1m Found rstudio-1.0.143-amd64.deb (B [m
 [1m [32m==> (B [m [1m Validating source files with md5sums... (B [m
    rstudio-1.0.143-amd64.deb ... Passed
 [1m [32m==> (B [m [1m Making package: rstudio-desktop-bin 1.0.143-2 (Fri Apr 28 17:36:28 CST 2017) (B [m
 [1m [32m==> (B [m [1m Checking runtime dependencies... (B [m
 [1m [32m==> (B [m [1m Installing missing dependencies... (B [m
error: target not found: gstreamer0.10-base
 [1m [31m==> ERROR: (B [m [1m 'pacman' failed to install missing dependencies. (B [m
 [1m [31m==> ERROR: (B [m [1m Build failed, check /var/lib/archbuild/extra-x86_64/lilydjwg/build (B [m

调用栈如下：

Traceback (most recent call last):
  File "/home/lilydjwg/soft/lilac/lilac", line 164, in build_package
    depends = DEPENDS.get(package, ()),
  File "/home/lilydjwg/soft/lilac/lilaclib.py", line 428, in lilac_build
    call_build_cmd(build_prefix, depend_packages, pkgs_to_build)
  File "/home/lilydjwg/soft/lilac/lilaclib.py", line 458, in call_build_cmd
    build_output = run_cmd(cmd, use_pty=True)
  File "/home/lilydjwg/soft/lilac/lilaclib.py", line 530, in run_cmd
    raise CalledProcessError(code, cmd, out)
subprocess.CalledProcessError: Command '['extra-x86_64-build', '--', '--', '--holdver']' returned non-zero exit status 255.
```

**Comment by SilverRainZ** [comment]
Because gstreamer0.10-base is an AUR dependence ?

**Comment by petronny** [comment]
因为你用的extra-x86_64
应该用archlinuxcn-x86_64

**Comment by xgdgsc** [comment]
Thanks!
