### ISSUE TITLE
firefox-kde-opensuse 打包失败（请勿使用网易邮箱）

### ISSUE THREAD

**Issue by lilydjwg** [archlinuxcn/repo#619]
### 问题类型 / Type of issues

* 其它 / other

### 受影响的软件包 / Affect packages

* firefox-kde-opensuse
----

firefox-kde-opensuse 57.0.2-1 已于 2017-12-21 21:58:03 打包失败。错误报告被网易退信。请自行于 ~lilydjwg/.lilac/log 下查阅相关日志。

**Comment by petronny** [comment]
呃，这就十分尴尬了啊。。。

**Comment by petronny** [comment]
检查了一下是端口占用的问题
```
/build/firefox-kde-opensuse/src/mozilla-unified/obj-x86_64-pc-linux-gnu/_virtualenv/bin/python /build/firefox-kde-opensuse/src/mozilla-unified/build/pgo/profileserver.py 10
Traceback (most recent call last):
  File "/build/firefox-kde-opensuse/src/mozilla-unified/build/pgo/profileserver.py", line 37, in <module>
    httpd.start(block=False)
  File "/build/firefox-kde-opensuse/src/mozilla-unified/testing/mozbase/mozhttpd/mozhttpd/mozhttpd.py", line 260, in start
    self.httpd = EasyServer((self.host, self.port), self.handler_class)
  File "/usr/lib64/python2.7/SocketServer.py", line 417, in __init__
    self.server_bind()
  File "/usr/lib64/python2.7/BaseHTTPServer.py", line 108, in server_bind
    SocketServer.TCPServer.server_bind(self)
  File "/usr/lib64/python2.7/SocketServer.py", line 431, in server_bind
    self.socket.bind(self.server_address)
  File "/usr/lib64/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
socket.error: [Errno 98] Address already in use
make[2]: *** [Makefile:345: pgo-profile-run] Error 1
```
具体来说是8888端口
```sh
$ sed -n '18p' src/mozilla-unified/build/pgo/profileserver.py
PORT = 8888
```
build机上占用这个的能改一下不。。？

**Comment by lilydjwg** [comment]
呃，它为什么不能自己挑一下没人用的呢……

**Comment by lilydjwg** [comment]
好了，改走了。

**Comment by petronny** [comment]
2f12d54
