### ISSUE TITLE
同步 arch-deepin

### ISSUE THREAD

**Issue by dongfengweixiao** [archlinuxcn/repo#82]
希望能够一起同步 https://github.com/fasheng/arch-deepin

**Comment by farseerfc** [comment]
他們不是已經有放在OBS上的repo了麼，直接用那個repo如何呀？

另外，只是我個人意見，剛剛試了一下那個repo，發現安裝dde會需要替換幾個arch原生的包爲ubuntu的包。
```
:: There are 6 members in group deepin-extra:
:: Repository home_metakcahura_arch-deepin_Arch_Extra
   1) deepin-game-center  2) deepin-movie  3) deepin-music-player  4) deepin-screenshot  5) deepin-terminal  6) deepin-vte

Enter a selection (default=all): 
:: There are 26 members in group deepin:
:: Repository home_metakcahura_arch-deepin_Arch_Extra
   1) dde-account-faces  2) dde-api  3) dde-control-center  4) dde-daemon  5) dde-dock-applets  6) dde-go-dbus-factory  7) dde-qml-dbus-factory
   8) dde-workspace  9) deepin-artwork  10) deepin-artwork-themes  11) deepin-compiz  12) deepin-cursor-theme  13) deepin-default-gsettings
   14) deepin-gtk-theme  15) deepin-icon-theme  16) deepin-menu  17) deepin-notifications  18) deepin-pygtk  19) deepin-qml-widgets
   20) grub-theme-deepin  21) libdeepin-webkit  22) lightdm-deepin-greeter  23) python2-deepin-gsettings  24) python2-deepin-ui
   25) python2-deepin-utils  26) startdde

Enter a selection (default=all): 
resolving dependencies...
looking for conflicting packages...
:: deepin-pygtk and pygtk are in conflict. Remove pygtk? [y/N] y
:: deepin-vte and vte are in conflict. Remove vte? [y/N] y
:: metacity-ubuntu and metacity are in conflict. Remove metacity? [y/N] y
:: lightdm and sddm are in conflict (display-manager). Remove sddm? [y/N] y

Packages (64) acpid-2.0.23-4  cddb-py-1.4-7  flattr-icon-theme-1.1-1  gstreamer0.10-ugly-0.10.19-14  gstreamer0.10-ugly-plugins-0.10.19-14
              libmediainfo-0.7.72-1  libzen-0.4.30-1  lightdm-1:1.14.0-1  mediainfo-0.7.72-1  metacity-3.14.3-1 [removal]
              metacity-ubuntu-2.34.13.0ubuntu4-107  mutagen-1.27-1  pygtk-2.24.0-5 [removal]  python2-ass-0.4.1-2  python2-jswebkit-0.0.3-4
              python2-magic-5.19-1  python2-mpd-0.3.0-5  python2-peewee-2.4.7-1  python2-pycurl-7.19.5.1-2  python2-pyquery-1.2.9-1
              python2-pysrt-1.0.1-1  python2-setproctitle-1.1.8-2  python2-wnck-2.32.0-15  python2-xpyb-1.3.1-1  python2-xpybutil-20130808.b030321-0
              qt5-systems-5.4.0.20141208.44f70d9-0  qtav-1.5.0-2  rfkill-0.5-1  sddm-0.11.0-1 [removal]  sonata-1.6.2.1-12  vte-0.28.2-5 [removal]
              xcur2png-0.7.1-2  dde-account-faces-1.0.7-1  dde-api-0.0.2.20150107093816-1  dde-control-center-0.1.20150211150410-1
              dde-daemon-0.0.1.20150209101554-1  dde-dock-applets-0.0.4.20150212175159-1  dde-go-dbus-factory-0.0.2.20141226160557-1
              dde-qml-dbus-factory-0.0.2.20141226160557-1  dde-workspace-2.1.20150202093855-1  deepin-artwork-2014-1
              deepin-artwork-themes-14.04.3.20141204110221-1  deepin-compiz-1:0.9.99.5.git20140707164843-1  deepin-cursor-theme-2014.4-1
              deepin-default-gsettings-0.2.20141216171821-1  deepin-game-center-1.0.1.20141230144448-1  deepin-gtk-theme-14.07.20141223164347-1
              deepin-icon-theme-13.06.13.20150114160019-1  deepin-menu-1.1.20141216195521-1  deepin-movie-2.2.20150211132515-1
              deepin-music-player-1.1.20150204093722-1  deepin-notifications-0.3.20141216180805-1  deepin-pygtk-2.24.0-6
              deepin-qml-widgets-0.0.2.20150203171526-1  deepin-screenshot-2.1.20141230110557-1  deepin-terminal-1.1.20141230110750-1
              deepin-vte-1:0.28.2-8  grub-theme-deepin-0.5-1  libdeepin-webkit-1.8.2.2.20141124213858-1  lightdm-deepin-greeter-2.1.20150202093855-1
              python2-deepin-gsettings-0.1.git20131206094009-1  python2-deepin-ui-1.1.20141229194712-1  python2-deepin-utils-0.0.2.20140703165416-1
              startdde-0.1.20141230181929-1

Total Download Size:    74.73 MiB
Total Installed Size:  325.10 MiB
Net Upgrade Size:      296.45 MiB

:: Proceed with installation? [Y/n] n
```

我有點害怕破壞現有程序的穩定性，不太敢裝……

**Comment by dongfengweixiao** [comment]
OBS有时候并不是太稳定，导致可能会出现一些异常，比如下载不下来，总是中断什么的。不过，这个是有独立的源的，其实不添加也没有什么太大的问题。

嗯，说一句题外话，archlinuxcn的repo的原则是什么？我记得之前看过，好像是：不容易安装（被功夫网X），不容易编译（需要进行交叉编译[lib32]），中文使用用户较多，因为一些其他的原因，导致对于中文用户需要使用一些奇奇怪怪的编译参数，有趣的（？）。谁可以答疑？

**Comment by lilydjwg** [comment]
那你应该请求镜像那个源。这事得找 @felixonmars 不过上一个镜像请求他没理会……

archlinuxcn 源的最基本原则是：没版权问题、有人维护。当然建议是对中文用户最有用的那些包了，毕竟人力有限。

**Comment by farseerfc** [comment]
我也想不起來在哪裏看到過了，我說得可能不權威僅供參考：

1. 首先要有社區打包組成員願意添加這個包並負責後續升級維護。 這一點最爲重要，因爲沒人維護的孤兒包即使添加進來，之後也會因爲過期沒人維護而被刪除。負責維護的人需要至少自己在用或者說能測試這個包是否正確打包，是否能用，所以沒有人用的包大概沒人會接收吧。當然歡迎有一定基礎的用戶來申請加入打包組，維護自己想用的包。

2. 如果打包的上游來源包含有需要分發協議的二進制，需要從來源獲取再分發許可之後方可打包上傳，具體見 [Wiki頁的規則](https://github.com/archlinuxcn/repo/wiki/%E8%A7%84%E5%88%99)

3. 因爲第一點的原因，所以需要打包簡單吧，打包複雜的包自然難以維護，不會有人接手咯。不過交叉編譯lib32這種其實還算簡單的，能不需要修改直接從aur打包，也沒有或者很少依賴aur裏的包的話都算簡單的。現在社區源有個半自動的打包機器人 lilac ，來自aur的包升級基本都可以交給 lilac 打理。

4. 不要和官方源 [extra] [community] 等的包重複，這個沒什麼好說的吧。

5. 如果有對應的非CVS的包，那麼似乎原則上不加入CVS的包（-git, -svn, -hg, -bzr 這些），因爲CVS的包更新頻發難以保證穩定，適合用戶自己從aur打包安裝。不過如果沒有穩定包對應的話那也可以有CVS的包（我自己就上傳了幾個）。

其它的，其實也是看打包組的成員的興趣吧，因爲成員裏中文用戶比較多所以和中文用戶相關的包也相對比較多，不過也有只會英文的打包組成員呀所以不絕對。

**Comment by xgdgsc** [comment]
看你在ustclug/mirrorrequest 提需求了，不行还可以找其他学校，这个思路是对的。个人上次试arch-deepin的时候觉得bug比较多，所以不看好会有大量用户，镜像这个意义不大。

**Comment by dongfengweixiao** [comment]
其实，某种程度上，这些东西都是极大的方便新手，对于我们来说，可能稍微的繁复点，但是并不影响正常的使用。

**Comment by farseerfc** [comment]
試了一下，其中deepin-movie和deepin-game-center都有打包問題不能用。
```console
 farseerfc  ~  repo  work  nautilus-dropbox  deepin-movie
file:///usr/share/deepin-movie/views/main.qml:69:5: Type PreferenceWindow unavailable 
         PreferenceWindow { id: preference_window } 
         ^
file:///usr/share/deepin-movie/views/PreferenceWindow.qml:265:13: Type HotKeyInputRow unavailable 
                 HotKeyInputRow { 
                 ^
file:///usr/share/deepin-movie/views/HotKeyInputRow.qml:50:9: Type HotKeyInput unavailable 
             HotKeyInput { 
             ^
file:///usr/share/deepin-movie/views/HotKeyInput.qml:4:1: Type DTextInput unavailable 
     DTextInput { 
     ^
file:///usr/lib/qt/qml/Deepin/Widgets/DTextInput.qml:191:5: Type DInputActions unavailable 
         DInputActions { 
         ^
file:///usr/lib/qt/qml/Deepin/Widgets/DInputActions.qml:2:1: module "DBus.Com.Deepin.Menu" is not installed 
     import DBus.Com.Deepin.Menu 1.0 
     ^
Traceback (most recent call last):
  File "/usr/bin/deepin-movie", line 105, in <module>
    windowView.initWindowSize()
  File "/usr/share/deepin-movie/views/window.py", line 78, in initWindowSize
    self.rootObject().initWindowSize()
AttributeError: 'NoneType' object has no attribute 'initWindowSize'
 farseerfc  ~  repo  work  nautilus-dropbox  deepin-game-center                                                                             1 
Xlib.protocol.request.QueryExtension
Traceback (most recent call last):
  File "/usr/bin/deepin-game-center", line 30, in <module>
    from game_center import GameCenterApp
  File "/usr/share/deepin-game/src/game_center.py", line 58, in <module>
    from download_manager import FetchInfo
  File "/usr/share/deepin-game/src/download_manager.py", line 28, in <module>
    from deepin_storm.services import FetchService
ImportError: No module named deepin_storm.services
```

**Comment by petronny** [comment]
这个源有一种硬要把arch装成deepin的感觉，或者说非得用pacman替代apt-get。感觉很扭曲。

AUR里面也有很多fasheng维护的deepin包。
可以改成添加这些包这个思路，毕竟有的人就为了用个deepin-music

这样就只有deepin-pygtk是个问题，music-player, game-center都依赖这个。
//其他不需要替换的包暂且不提
