### ISSUE TITLE
Packaging error python2-pyside2

### ISSUE THREAD

**Issue by a-wing** [archlinuxcn/repo#965]
### 问题类型 / Type of issues

* 打包错误 / packaging error

### 受影响的软件包 / Affected packages

* python2-pyside2

----
```
======================================================================
FAIL: test_pkgbuild (__main__.ConfigSectionTest) (line='groups = qt', package='python2-pyside2')
----------------------------------------------------------------------
Traceback (most recent call last):
  File "./pre-commit", line 372, in check_var_srcinfo
    ','.join(against[pkg])))
AssertionError: 'groups = qt' == 'groups = qt' : PKGBUILD of package "python2-pyside2" contains "groups = qt" in "extra" repo
======================================================================
FAIL: test_pkgbuild (__main__.ConfigSectionTest) (line='groups = qt5', package='python2-pyside2')
----------------------------------------------------------------------
Traceback (most recent call last):
  File "./pre-commit", line 372, in check_var_srcinfo
    ','.join(against[pkg])))
AssertionError: 'groups = qt5' == 'groups = qt5' : PKGBUILD of package "python2-pyside2" contains "groups = qt5" in "extra" repo
----------------------------------------------------------------------
Ran 9 tests in 36.580s
FAILED (failures=2, skipped=3)
```
https://travis-ci.org/archlinuxcn/repo/builds/469338529?utm_source=github_status&utm_medium=notification

**Comment by BruceZhang1993** [comment]
It seems ok now. ci has passed.
