### ISSUE TITLE
Jekyll 找不到依赖 eventmachine 1.2.7

### ISSUE THREAD

**Issue by RedL0tus** [archlinuxcn/repo#980]
### 问题类型 / Type of issues

* 打包错误 / packaging error

### 受影响的软件包 / Affected packages

* jekyll

----

请在此补充说明。
Please describe in detail here.

Jekyll 依赖一个叫 eventmachine 的 gem，系统也安装上了这个包，irb 里能 require 对应的包但是 jekyll 找不到。

```
Traceback (most recent call last):
        12: from /usr/bin/jekyll:23:in `<main>'
        11: from /usr/bin/jekyll:23:in `load'
        10: from /usr/lib/ruby/gems/2.5.0/gems/jekyll-3.8.5/exe/jekyll:11:in `<top (required)>'
         9: from /usr/lib/ruby/gems/2.5.0/gems/jekyll-3.8.5/lib/jekyll/plugin_manager.rb:50:in `require_from_bundler'
         8: from /usr/lib/ruby/gems/2.5.0/gems/bundler-1.17.3/lib/bundler.rb:107:in `setup'
         7: from /usr/lib/ruby/gems/2.5.0/gems/bundler-1.17.3/lib/bundler/runtime.rb:20:in `setup'
         6: from /usr/lib/ruby/gems/2.5.0/gems/bundler-1.17.3/lib/bundler/runtime.rb:108:in `block in definition_method'
         5: from /usr/lib/ruby/gems/2.5.0/gems/bundler-1.17.3/lib/bundler/definition.rb:226:in `requested_specs'
         4: from /usr/lib/ruby/gems/2.5.0/gems/bundler-1.17.3/lib/bundler/definition.rb:237:in `specs_for'
         3: from /usr/lib/ruby/gems/2.5.0/gems/bundler-1.17.3/lib/bundler/definition.rb:170:in `specs'
         2: from /usr/lib/ruby/gems/2.5.0/gems/bundler-1.17.3/lib/bundler/spec_set.rb:85:in `materialize'
         1: from /usr/lib/ruby/gems/2.5.0/gems/bundler-1.17.3/lib/bundler/spec_set.rb:85:in `map!'
/usr/lib/ruby/gems/2.5.0/gems/bundler-1.17.3/lib/bundler/spec_set.rb:91:in `block in materialize': Could not find eventmachine-1.2.7 in any of the sources (Bundler::GemNotFound)

```

**Comment by SilverRainZ** [comment]
`jekyll <- ruby-em-websocket <- ruby-eventmachine`。

是什么导致了你的机器上有 jekyll 而没有  ruby-eventmachine？

**Comment by RedL0tus** [comment]
> `jekyll <- ruby-em-websocket <- ruby-eventmachine`。
> 
> 是什么导致了你的机器上有 jekyll 而没有 ruby-eventmachine？

刚刚看了下这个包是存在的... 但是 Jekyll 找不到...

**Comment by SilverRainZ** [comment]
抱歉，我本地没能复现。
先 reopen 吧。

**Comment by RedL0tus** [comment]
我也不知道是什么毛病，看 gem 目录下面是可以找到对应的包的，irb 里手动 require 也能成功载入，但是 jekyll 就是找不到...

**Comment by SilverRainZ** [comment]
抱歉，问题确实是出在打包上，上个月末 arch 的 ruby 升级到了 2.6.0，cn 源的 ruby 包没有跟着 rebuild 所以导致了这个问题，解决 #1013 后 jekyll 应该就能正常使用了。

**Comment by RedL0tus** [comment]
好的，谢谢（

**Comment by RedL0tus** [comment]
> Jekyll 3.8.5 已进源，请问问题还存在么？

现在是找不到 bundler 了 🙈
```
Traceback (most recent call last):
        5: from /usr/bin/jekyll:23:in `<main>'
        4: from /usr/bin/jekyll:23:in `load'
        3: from /usr/lib/ruby/gems/2.6.0/gems/jekyll-3.8.5/exe/jekyll:11:in `<top (required)>'
        2: from /usr/lib/ruby/gems/2.6.0/gems/jekyll-3.8.5/lib/jekyll/plugin_manager.rb:48:in `require_from_bundler'
        1: from /usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require': cannot load such file -- bundler (LoadError)
```

**Comment by RedL0tus** [comment]
这就不清楚了... 可能是我以前弄错了什么，先 close 吧
